# -*- coding: utf-8 -*-
"""Crowe & Cooper International.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1menC_adKSZ-aZff1fpalxtAsINUzIdid

# **1.INTRODUCTION**

**PROJECT SUMMARY**

The Marketing team of Crowe & Cooper International is analysing different digital marketing strategies to provide a more balanced
growth in the future, combining traditional online promotion with more advance social media
tactics.

In particular, the Marketing department has teamed up with other divisions such as Finance,
Audit, Tax and Advisory, to explore how more modern digital marketing strategies can provide the
basis for developing effective client engagement strategies. As in most strategy development
processes, three steps are needed:

i. First understand where the company stands now,

ii. Second define strategic objectives and,

iii. Third develop the approaches/initiatives/tactics to achieve these strategic objectives.

The purpose of this project is to analyse Crowe & Cooper International’s current business performance .
"""

# import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
pd.options.display.float_format = '{:,.2f}'.format

# import the crowe & cooper dataset
file_path = '/content/Crowe  Cooper dataset Original .xlsx'
df =pd.read_excel(file_path)

# overview of the dataset
df.head(5)

#datatypes
df.info()

#missing values?
df.isna().sum()

"""
# **2. DATA CLEANING AND PREPROCESSING**"""

# rename some columns
df.rename(columns={
 'Client industry sectors': 'Sector',
  'Revenue (£000)' : 'Revenue',
   'Number of projects' : 'Projects'
}, inplace=True)

df['Sector'].unique()

df['Region'].unique()

# map inconsistent names and year
map_region = {'North America': 'North America', 'North Amer£c@': 'North America', 'Western Europe': 'Western Europe', 'Middle East': 'Middle East' }

df['Region'] = df['Region'].map(map_region)


# mpan year
map_year = {2052:2024, 2022:2022, 2023:2023, 2024:2024}
df['Year'] = df['Year'].map(map_year)



map_sectors = {'IT and Telecom': 'IT and Telecom', 'Manufacturing':'Manufacturing', 'Healthcare':'Healthcare', 'Public and Government':'Public and Government', 'Finance':'Finance', 'Energy': 'Energy', 'Manufact$$$$$$':'Manufacturing', 'Finan£$%':'Finance' }

df['Sector'] = df['Sector'].map(map_sectors)

df['Sector'].unique()

df['Year'].unique()

df['Region'].unique()

# create a new column, Year_month
df['Year_month'] = pd.to_datetime(df[['Year', 'Month']].assign(Day=1))

# create a new column, quarter

df['Quarter'] = pd.to_datetime(df['Month'], format='%m').dt.quarter

df.info()

# change Year_month to a string
df['Year_month'] = df['Year_month'].dt.to_period('M').astype(str)

# treat missing values
df[df['Revenue'].isna()]

df[(df['Region']=='North America') & (df['Year']==2022) & df['Sector'].isin(['Public and Government'])]

# replace missing values with median of region, year and sector
df['Revenue'] = df['Revenue'].fillna(
    df.groupby(['Region', 'Year', 'Sector'])['Revenue'].transform('median')
)


df['Projects'] = df['Projects'].fillna(
    df.groupby(['Region', 'Year', 'Sector'])['Projects'].transform('median')
)

df.isna().sum()

df[(df['Region']=='North America') & (df['Year']==2022) & df['Sector'].isin(['Public and Government'])]

"""# **3. EXPLORATORY DATA ANALYSIS**"""



"""i. Data and trends in total project volume and revenue
by month, by year across the 3 years period.



ii. Benchmark comparisons of project volume and
revenue between regions by quarter, by year across
the 3-year period.



iii. Benchmark comparisons of client sectors
performance covering project volume and revenue
by quarter, by year across the 3-year period
"""

# i. Data and trends in total project volume and revenue by month, by year across the 3 years period.


df.groupby( ['Year', 'Month']
)[['Projects', 'Revenue']].agg('sum')

"""**INSIGHTS**


i. 2024 has the highest number of projects and revenues in all except a few months and demonstrates a good growth pattern.

ii. 2022 was better than 2023 in Month 10 and 11, for instance, suggesting that 2023 might have been a year when the operation reorganized or slowed down.

iii. August has the highest revenue of £1,149,557.60k, suggesting a peak season.

iv. February has the lowest revenue of £985,327.20k, perhaps due to fewer working days or project cycles.

"""

df.groupby('Year')[['Revenue', 'Projects']].agg('sum')

# ii. Benchmark comparisons of project volume and revenue between regions by quarter, by year across the 3-year period.

region_trends = pd.pivot_table(
   df,
   values= ['Revenue', 'Projects'],
   index= ['Region', 'Year', ], #'Quarter'],
   aggfunc='sum',
   columns= 'Quarter',
   margins=True,
   margins_name='Total'

)

region_trends



"""**INSIGHTS**

i. Western Europe leads all regions with the highest total revenue (£5.06M) and projects (95,148), peaking in 2024 with exceptional Q4 performance (£579k revenue, 11,228 projects).


ii. North America shows consistent year-over-year growth, rising from £1.08M in 2022 to £1.56M in 2024.


iii. Middle East peaked in 2022 (£1.68M revenue, 30,522 projects), then declined in 2023, but partially recovered in 2024 (£1.28M, 28,060 projects), though not back to 2022 levels.

iv. 2024 was the best year overall for all three regions in terms of both revenue and project volume, suggesting a broader market upswing or effective scaling strategies.

v. Quarterly trend: Q4 2024 stands out across regions for delivering record revenues and project counts, especially in Western Europe and North America.

vi. Middle East volatility is notable — a sharp dip in 2023 across all quarters signals potential market disruption, with Q2 2022 being the region’s single strongest quarter.


"""

# Benchmark comparisons of client sectors performance covering project volume and revenue by quarter, by year across the 3-year period


sector_trends = pd.pivot_table(
   df,
   values= ['Revenue', 'Projects'],
   index= ['Sector', 'Year', ], #'Quarter'],
   aggfunc='sum',
   columns= 'Quarter',
   margins=True,
   margins_name='Total'

)

sector_trends

"""**INSIGHTS**

i. Finance: Highest revenue (£2.9M) and 73,125 projects; peak in 2024 (£1.18M, 30,415 projects); strong Q4 2024 (£350k+, 9,540 projects).

ii. Public & Government: £2.5M revenue, highest volume (83,791 projects); peak in 2024 (33,361 projects) after 2023 dip.

iii. Healthcare: £2.47M from 27,288 projects; steady decline in 2024 suggests budget cuts or normalization.

iv. IT & Telecom: £1.92M, 19,157 projects; dipped in 2023, recovered in Q3–Q4 2024.

v. Manufacturing & Energy: Manufacturing rose from £553k (2022) to £801k (2024); Energy lowest volume (19,573), but strong Q4 2024 rebound.
"""



"""**CASE**

In January 2024 the
company established an equity partnership with UK-based One-click Media Group, a social media
marketing agency specialised in B2B social media for the European market. The idea of the
partnership is to allow Crowe & Cooper International to quickly acquire for the Western Europe
region marketing capabilities in the social media arena, such as brand positioning, content
promotion, recruitment activity and direct lead generation.
The Marketing Director is keen to understand if the business model used in Western Europe with
One-click Media Group could be applied to other regions, so that similar partnerships with regional
social media marketing agencies can be established.



Did the equity partnership with One-click Media Group, which brought social media know-
how to the operations in Western Europe, increase the revenue and overall performance of
the region?
"""

# Did the equity partnership with One-click Media Group, which brought social media know-how to the operations in Western Europe, increase the revenue and overall performance of the region?




WE = df[df['Region']=='Western Europe'].groupby('Year')[['Revenue', 'Projects']].agg('sum')
WE['Revenue change %'] = WE['Revenue'].pct_change()*100
WE['Project change %'] = WE['Projects'].pct_change()*100
WE

"""**Interpretation**

In 2023 (pre-partnership), both revenue and project volume declined slightly.

In 2024 (post-partnership)

  -Revenue increased by 33.08%

  -Project volume rose by 22.34%

This significant turnaround aligns directly with the timing of the January 2024 equity partnership with One-click Media Group.




**Conclusion**


Yes, the equity partnership with One-click Media Group appears to have had a positive and substantial impact on both revenue and performance in Western Europe.
This suggests the business model — leveraging a specialized social media marketing partner — was effective and may be worth replicating in other regions to achieve similar performance gains.
"""

df.columns.to_list()

"""**VISUALIZATION**"""



# 1. Revenue and Projects trends over time

plt.figure(figsize=(20,6))

plt.subplot(1,2,1)
sns.lineplot(data=df, x='Year_month', y='Revenue', hue='Region', ci=None)
plt.title('Revenue Trends Over Time')
plt.xlabel('Time')
plt.ylabel('Revenue (£000)')
plt.xticks(rotation=45)



# Projects
plt.subplot(1,2,2)
sns.lineplot(data=df, x='Year_month', y='Projects', hue='Region', ci=None)
plt.title('Project Trends Over Time')
plt.xlabel('Time')
plt.ylabel('Number of Projects')
plt.xticks(rotation=45)


plt.tight_layout()
plt.show()

"""**Western Europe**



*   Clear upward trajectory, especially in 2024.
*   Sharp dip in early 2024, likely January, followed by strong recovery and consistent growth.

*   This aligns with the equity partnership with One-click Media Group (January 2024).


**North America**


*   Shows moderate and steady growth over the period.
*   Some seasonal fluctuation, but overall relatively stable trend.



**Middle East**



*   Volatile trend with sharp peaks and troughs
*   A dramatic drop in mid-2022, suggesting a one-time issue

*   Struggles to recover in 2023, but some modest rebound in 2024.











"""

# Quarterly Trends Over Time

quarterly_trends = df.groupby(['Year', 'Quarter', 'Region'])[['Revenue', 'Projects']].agg('sum').reset_index()


plt.figure(figsize=(10,6))
sns.barplot(data=quarterly_trends, x='Quarter', y='Revenue', hue='Region')
plt.title('Quarterly Trends Over Time Across Regions')
plt.tight_layout()
plt.show()

"""**INSIGHTS**

i. Western Europe consistently outperforms the other regions in revenue across all quarters, with steady growth from Q1 to Q4.

ii. North America shows a gradual upward trend, improving from Q1 to Q4, though always trailing behind Western Europe.

iii. Middle East starts strong in Q1 and Q2 but declines in Q3 and Q4, indicating a possible performance drop in the second half of the year.
"""

# Trends across different sectors


sector_trends = df.groupby(['Year', 'Quarter', 'Sector'])[['Revenue', 'Projects']].agg('sum').reset_index()

plt.figure(figsize=(20,6))

plt.subplot(1, 2, 1)
sns.barplot(data=sector_trends, x='Year', y='Revenue', hue='Sector')
plt.xlabel('Time')
plt.ylabel('Revenue (£000)')
plt.title('Sector Trends Over Time')


# lineplot
plt.subplot(1,2,2)
sns.lineplot(data=df, x='Year_month', y='Revenue', hue='Sector', ci=None)
plt.title('Sector Trends Over Time')
plt.xlabel('Time')
plt.ylabel('Revenue (£000)')
plt.xticks(rotation=45)


plt.tight_layout()
plt.show()

"""**INSIGHTS**

i. Finance shows the strongest upward trend, with consistent and substantial growth year over year.

ii. Healthcare peaked in 2022 but declined steadily through 2023 and 2024.

iii. Public and Government and Manufacturing both showed significant recovery in 2024 after a dip in 2023.

iii. Energy remained relatively stable and lower than other sectors across all years, while IT and Telecom rebounded slightly in 2024 after a drop in 2023.
"""

# Quarterly Trends Over Time Across Sectors

quarterly_trends_sector = df.groupby(['Year', 'Quarter', 'Sector'])[['Revenue', 'Projects']].agg('sum').reset_index()


plt.figure(figsize=(10,6))
sns.barplot(data=quarterly_trends_sector, x='Quarter', y='Revenue', hue='Sector')
plt.title('Quarterly Trends Over Time Across Sectors')
plt.ylabel('Revenue (£000)')
plt.tight_layout()
plt.show()

"""**INSIGHTS**

i. Finance consistently leads in revenue across all quarters, with Q3 being its peak.

ii. Healthcare shows a slight downward trend from Q1 to Q3 but recovers slightly in Q4.

iii. Public and Government remains stable and strong throughout the year, especially in Q3 and Q4.

iv. Energy has the lowest revenue overall but shows a small upward trend in Q4, indicating a mild year-end recovery.

# **4. CONCLUSION**

Crowe & Cooper International’s marketing team is exploring enhanced digital strategies by integrating traditional methods with advanced social media tactics. Collaborating with Finance, Audit, Tax and Advisory divisions, the goal is to boost client engagement and long-term growth. The project begins by assessing the company’s current performance, followed by setting strategic goals and outlining tactics to achieve them. The report includes data cleaning, preprocessing, and exploratory analysis of project volumes and revenues across sectors, regions and time periods. Key insights guide strategic marketing adjustments, aiming to improve business outcomes through data-driven decision-making and cross-functional collaboration.
"""

df.to_csv('Crowe & Cooper International.csv', index=False)